disabled_rules:
    - switch_case_alignment
    - unused_optional_binding
    - identifier_name
    - type_name

included:
    - redditweaks
    - redditweaks Extension

excluded:
    - .build
    - fastlane

