name: Swift Test & Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme redditweaks && xcodebuild -scheme redditweaks\ Extension
    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3
